import Link from "next/link";
import styles from "./construction-tools.module.css";

const TOOLS = [
    {
        title: "Project Cost Calculator",
        description:
            "Estimate material, labour, equipment, P&G, overhead, contingency, and VAT for your construction project using current Nigerian market rates.",
        href: "/services/tools/cost-calculator",
        icon: "📊",
        features: ["Cost breakdown chart", "PDF export", "AI explanation"],
    },
    {
        title: "Material Calculator",
        description:
            "Calculate exact quantities for concrete, blocks, plaster, flooring, and steel reinforcement with Nigerian QS standard formulas.",
        href: "/services/tools/material-calculator",
        icon: "🧱",
        features: ["5 material types", "Wastage included", "Unit conversion"],
    },
    {
        title: "Instant Quote Generator",
        description:
            "Generate a professional preliminary quote in minutes — capture client details, select project options, and get an instant cost estimate.",
        href: "/services/tools/instant-quote",
        icon: "📋",
        features: ["Multi-step wizard", "WhatsApp share", "Quote submission"],
    },
    {
        title: "Project Timeline Estimator",
        description:
            "Estimate delivery duration with phase-by-phase breakdown considering crew size, weather risk, permits, and site conditions.",
        href: "/services/tools/timeline-estimator",
        icon: "📅",
        features: ["Phase timeline", "Weather factors", "Duration warnings"],
    },
];

const ConstructionToolsHub = () => {
    return (
        <div className={styles.hubWrapper}>
            {/* Hero Section */}
            <section className={styles.hubHero}>
                <div className={styles.hubHeroContent}>
                    <span className={styles.hubBadge}>🏗️ Estimation Tools</span>
                    <h1 className={styles.hubHeading}>
                        Construction Estimation &amp; Planning Tools
                    </h1>
                    <p className={styles.hubSubheading}>
                        Get instant preliminary estimates for your construction project — cost, materials,
                        quotes, and timelines. Built with Nigerian market data and powered by AI.
                    </p>
                    <div className={styles.hubStats}>
                        <div className={styles.hubStat}>
                            <strong>4</strong>
                            <span>Estimation Tools</span>
                        </div>
                        <div className={styles.hubStat}>
                            <strong>NGN</strong>
                            <span>Nigerian Rates</span>
                        </div>
                        <div className={styles.hubStat}>
                            <strong>AI</strong>
                            <span>Smart Explanations</span>
                        </div>
                    </div>
                </div>
            </section>

            {/* Tools Grid */}
            <section className={styles.hubGrid}>
                {TOOLS.map((tool, index) => (
                    <Link key={tool.href} href={tool.href} className={styles.hubCardLink}>
                        <div className={styles.hubCard}>
                            <div className={styles.hubCardIcon}>{tool.icon}</div>
                            <div className={styles.hubCardNumber}>0{index + 1}</div>
                            <h3 className={styles.hubCardTitle}>{tool.title}</h3>
                            <p className={styles.hubCardDesc}>{tool.description}</p>
                            <div className={styles.hubCardFeatures}>
                                {tool.features.map((f) => (
                                    <span key={f} className={styles.hubFeatureBadge}>{f}</span>
                                ))}
                            </div>
                            <div className={styles.hubCardAction}>
                                Open Tool <span>→</span>
                            </div>
                        </div>
                    </Link>
                ))}
            </section>

            {/* Disclaimer */}
            <section className={styles.hubDisclaimer}>
                <p>
                    <strong>⚠️ Important:</strong> All estimates generated by these tools are for preliminary
                    planning purposes only. Final cost, quantities, and duration will be confirmed after detailed
                    engineering design, bill of quantities preparation, site inspection, and current market pricing.
                    All figures are exclusive of land cost.
                </p>
            </section>
        </div>
    );
};

export default ConstructionToolsHub;

